# ═══════════════════════════════════════════════════════════════════════════
# sources.yml - External Bronze Layer Sources
# Parquet files gerados pelos scrapers VTEX
# ═══════════════════════════════════════════════════════════════════════════

version: 2

sources:
  # ─────────────────────────────────────────────────────────────────────────
  # BISTEK SUPERMARKET
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_bistek
    description: >
      Bronze layer data from Bistek supermarket scraper (VTEX platform).
      Raw product data scraped daily from 13 regions in Florianópolis.

    meta:
      source_owner: Alan Ludke
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: daily
      data_location: data/bronze/supermarket=bistek/

    tables:
      - name: products
        description: Raw product catalog with prices and availability per region
        external:
          location: '../../../../data/bronze/supermarket=bistek/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365  # days

        columns:
          - name: productId
            description: Unique product identifier from VTEX

          - name: productName
            description: Product name as displayed in e-commerce

          - name: brand
            description: Product brand

          - name: items
            description: Nested array of product variants (SKUs)

          - name: _metadata_supermarket
            description: Injected metadata - store name (bistek)

          - name: _metadata_region
            description: Injected metadata - region code (e.g. florianopolis_costeira)

          - name: _metadata_run_id
            description: Scraper run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was scraped

  # ─────────────────────────────────────────────────────────────────────────
  # FORT ATACADISTA
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_fort
    description: >
      Bronze layer data from Fort Atacadista scraper (VTEX platform).
      Raw product data scraped daily from 7 regions in Santa Catarina.

    meta:
      source_owner: Alan Ludke
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: daily
      data_location: data/bronze/supermarket=fort/

    tables:
      - name: products
        description: Raw product catalog with prices and availability per region
        external:
          location: '../../../../data/bronze/supermarket=fort/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365

        columns:
          - name: productId
            description: Unique product identifier from VTEX

          - name: productName
            description: Product name as displayed in e-commerce

          - name: brand
            description: Product brand

          - name: items
            description: Nested array of product variants (SKUs)

          - name: _metadata_supermarket
            description: Injected metadata - store name (fort)

          - name: _metadata_region
            description: Injected metadata - region code

          - name: _metadata_run_id
            description: Scraper run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was scraped

  # ─────────────────────────────────────────────────────────────────────────
  # GIASSI SUPERMERCADOS
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_giassi
    description: >
      Bronze layer data from Giassi Supermercados scraper (VTEX platform).
      Raw product data scraped daily from 17 regions in Santa Catarina.

    meta:
      source_owner: Alan Ludke
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: daily
      data_location: data/bronze/supermarket=giassi/

    tables:
      - name: products
        description: Raw product catalog with prices and availability per region
        external:
          location: '../../../../data/bronze/supermarket=giassi/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365

        columns:
          - name: productId
            description: Unique product identifier from VTEX

          - name: productName
            description: Product name as displayed in e-commerce

          - name: brand
            description: Product brand

          - name: items
            description: Nested array of product variants (SKUs)

          - name: _metadata_supermarket
            description: Injected metadata - store name (giassi)

          - name: _metadata_region
            description: Injected metadata - region code

          - name: _metadata_run_id
            description: Scraper run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was scraped

  # ─────────────────────────────────────────────────────────────────────────
  # CARREFOUR
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_carrefour
    description: >
      Bronze layer data from Carrefour scraper (VTEX platform with HTML scraping).
      Raw product data scraped from 5 regions in Santa Catarina.
      Note: Uses HTML scraping due to API 503 blocking.

    meta:
      source_owner: Alan Ludke
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: daily
      data_location: data/bronze/supermarket=carrefour/
      scraping_method: html_json_ld  # Special: HTML scraping with JSON-LD extraction
      api_blocked: true  # VTEX API returns 503

    tables:
      - name: products
        description: Raw product catalog with prices and availability per region (HTML scraped)
        external:
          location: '../../../../data/bronze/supermarket=carrefour/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365
          known_limitations: >
            - ListPrice = Price (no promotion data from JSON-LD)
            - Availability may be generic (no region-specific cookies)
            - ~27% 404 rate on inactive products

        columns:
          - name: productId
            description: Unique product identifier from VTEX

          - name: productName
            description: Product name as displayed in e-commerce

          - name: brand
            description: Product brand

          - name: items
            description: Nested array of product variants (SKUs)

          - name: _metadata_supermarket
            description: Injected metadata - store name (carrefour)

          - name: _metadata_region
            description: Injected metadata - region code

          - name: _metadata_run_id
            description: Scraper run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was scraped

  # ─────────────────────────────────────────────────────────────────────────
  # ANGELONI
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_angeloni
    description: >
      Bronze layer data from Angeloni scraper (VTEX platform with HTML scraping).
      Raw product data scraped from 3 regions in Santa Catarina (Florianópolis Centro/Continente, São José).
      Note: Uses HTML scraping due to API blocking.

    meta:
      source_owner: Alan Ludke
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: daily
      data_location: data/bronze/supermarket=angeloni/
      scraping_method: html_parsing  # HTML scraping with class-based selectors
      api_blocked: true  # VTEX API blocked

    tables:
      - name: products
        description: Raw product catalog with prices and availability per region (HTML scraped)
        external:
          location: '../../../../data/bronze/supermarket=angeloni/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365
          known_limitations: >
            - Brand field may show product name instead of actual brand (HTML parsing limitation)
            - EAN may be empty (requires enrichment)
            - ListPrice = Price (no promotion data from HTML)

        columns:
          - name: productId
            description: Unique product identifier from VTEX

          - name: productName
            description: Product name as displayed in e-commerce

          - name: brand
            description: Product brand (may be incomplete from HTML parsing)

          - name: items
            description: Nested array of product variants (SKUs)

          - name: _metadata_supermarket
            description: Injected metadata - store name (angeloni)

          - name: _metadata_region
            description: Injected metadata - region code

          - name: _metadata_run_id
            description: Scraper run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was scraped

  # ─────────────────────────────────────────────────────────────────────────
  # OPENFOODFACTS (GLOBAL EAN DATABASE)
  # ─────────────────────────────────────────────────────────────────────────
  - name: bronze_openfoodfacts
    description: >
      Bronze layer from OpenFoodFacts API.
      Global EAN reference database with nutritional data, product names,
      brands, and Nutriscore ratings. Used to enrich VTEX products with
      canonical names and nutritional information.

    meta:
      source_owner: OpenFoodFacts Community
      area_owner: Data Engineering
      email_owner: data-engineering@market-scraper.local
      refresh_frequency: weekly
      data_location: data/bronze/supermarket=openfoodfacts/

    tables:
      - name: products
        description: >
          Product data enriched from OpenFoodFacts API.
          Contains EAN codes, canonical product names, nutritional scores,
          and product attributes for global food products.
        external:
          location: '../../../../data/bronze/supermarket=openfoodfacts/**/*.parquet'
          file_format: parquet

        meta:
          contains_pii: false
          data_retention: 365  # days

        columns:
          - name: code
            description: EAN barcode (8, 13, or 14 digits)

          - name: product_name
            description: Canonical product name from OpenFoodFacts

          - name: brands
            description: Product brand(s)

          - name: categories
            description: Product categories (comma-separated)

          - name: quantity
            description: Net weight (e.g., "500g", "1.5kg")

          - name: nutriscore_grade
            description: Nutriscore rating (a=best, e=worst)

          - name: countries
            description: Country of origin

          - name: _metadata_supermarket
            description: Injected metadata - source name (openfoodfacts)

          - name: _metadata_region
            description: Injected metadata - region (global)

          - name: _metadata_run_id
            description: Enrichment run identifier for traceability

          - name: _metadata_scraped_at
            description: Timestamp when data was fetched from API
